ecs_cluster_name = "malik-ecs-cluster-prod"
ecs_service_name = "malik-ecs-service-prod"
ecs_task_defn_family = "malik-ecs-task-def-prod"
ecs_container_name = "malik-container-prod"
ecs_port_name = "malik-3000-tcp-prod"